hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - v2609_asr
  - data/train_data/bad_mix13k_openml_verb_lid05
  - _self_

reward_functions:
  openml:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      reduce: mean
      measures:
        char: {beta: 0.5}
        word: {beta: 0.5}
        lang: {beta: 1.0}
        fmt: {beta: 1.0}
        bracket: {beta: 1.0}
        repeat: {beta: 1.0}
        # tail_hallu: {beta: 1.0}

reward_function_by_data_source:
  mix: openml
  openml: openml

data:
  train_batch_size: 256