hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - grpo_asr_full
  - _self_
  # - data/train_data/local
  # - data/train_data/local_debug_parquet
  - data/train_data/local_debug_chunk
  - data/val_data/local

val_reward:
  custom_reward_function:
    # path: recipe/phimm/reward/asr_bias.py
    path: recipe/phimm/reward/asr_bias.py
    name: compute_score
    reward_kwargs:
      beta: 0.0 # score = WER + beta*B-WER
      choice: "err" # "err", "acc", "wer"
      text_norm: english # english (default), identity, lower, basic, simple, simple_with_tag
      unit: word # word (default), char

train_reward:
  reward_model:
    reward_manager: naive #required
  custom_reward_function:
    # path: recipe/phimm/reward/asr_bias.py
    path: recipe/phimm/reward/asr_bias.py
    name: compute_score
    reward_kwargs:
      beta: 1.0 # score = WER + beta*B-WER
      choice: "err" # "err", "acc", "wer"
      text_norm: english # english (default), identity, lower, basic, simple, simple_with_tag
      unit: word # word (default), char
      # error_book: true # whether to return error book for each sample
data:
  train_batch_size: 8

actor_rollout_ref:
  rollout:
    n: 4
    gpu_memory_utilization: 0.3
    gt_rollout: true
    calculate_log_probs: True
    # temperature: 10
  actor:
    loss_agg_mode: seq-mean-token-sum-norm
    tis_imp_ratio_cap: 5
    ppo_epochs: 1
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
algorithm:
  filter_groups:
    enable: false
  norm_adv_by_std_in_grpo: False
  norm_adv_by_mean_in_grpo: False
  adv_estimator: remax

trainer:
  experiment_name: dapo-phimm-test-lora-new
  save_freq: 100000
  test_freq: 10000
  val_before_train: false
  # resume_mode: "auto"
  resume_mode: "disable"
  default_hdfs_dir: null
  # total_training_steps: 10
