hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - data/train_data/prod_fy22
  - data/val_data/entity
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  reward_kwargs:
    beta: 5 # score = WER + beta*B-WER
    choice: "err" # "err", "acc", "wer"
    text_norm: simple # english (default), identity, lower, basic, simple, simple_with_tag
    unit: word # word (default), char
    max_err: 10 # only accept if error count <= max_err
actor_rollout_ref:
  rollout:
    n: 8
  model:
    path: ${oc.env:DATA_PATH}/boren/data/ckp/hf_models/Phi-4-multimodal-instruct
data:
  train_batch_size: 64
  gen_batch_size: 128
  total_training_steps: 2200 # ~= 140k samples with bs64, 0.5 epoch
