hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - data/train_data/ls_raw
  - data/val_data/ls_raw
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  # reward_kwargs:
  #   beta: 0.0 # score = (1-beta)*WER + beta*B-WER
  #   choice: "err" # "err", "acc", "wer"
  #   text_norm: simple # english (default), identity, lower, basic, simple, simple_with_tag
  #   unit: word # word (default), char
actor_rollout_ref:
  model:
    patch_phi4mm: false # skip for lora merged
    path: ${oc.env:DATA_PATH}/boren/data/ckp/hf_models/phi4_mm_bias_merged
  rollout:
    n: 8

data:
  train_batch_size: 8
  gen_batch_size: 16
