hydra:
  searchpath:
    - file://recipe/phimm/config/template
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - _self_
  - data/train_data/local
  - data/val_data/local

data:
  custom_cls:
    path: recipe/phimm/data/rl_dataset.py
    name: RLHFDataset
custom_reward_function:
  # path: recipe/phimm/reward/asr_bias.py
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  # reward_kwargs:
  #   beta: 0.0 # score = (1-beta)*WER + beta*B-WER
  #   choice: "err" # "err", "acc", "wer"
  #   text_norm: simple # english (default), identity, lower, basic, simple, simple_with_tag
  #   unit: word # word (default), char

actor_rollout_ref:
  model:
    lora_rank: 320
    lora_alpha: 640
    target_modules: "model.layers.*(qkv_proj|o_proj|gate_up_proj|down_proj).*"
    exclude_modules: "model.embed_tokens_extend.*" # must have
  rollout:
    gpu_memory_utilization: 0.3

trainer:
  experiment_name: dapo-phimm-test-lora-new
  save_freq: 1000
  test_freq: 1
  val_before_train: true
  resume_mode: disable
