hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - _self_
  - data/train_data/local
  - data/val_data/local

custom_reward_function:
  # path: recipe/phimm/reward/asr_bias.py
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  reward_kwargs:
    beta: 0.0 # score = WER + beta*B-WER
    choice: "err" # "err", "acc", "wer"
    text_norm: simple # english (default), identity, lower, basic, simple, simple_with_tag
    unit: word # word (default), char
    max_err: 2

actor_rollout_ref:
  rollout:
    gpu_memory_utilization: 0.3
  actor:
    loss_agg_mode: seq-mean-token-sum-norm
    use_kl_loss: False

algorithm:
  norm_adv_by_std_in_grpo: False

trainer:
  experiment_name: dapo-phimm-test-lora-new
  save_freq: 1000
  test_freq: 1
  val_before_train: true
  resume_mode: disable
