data:
  train_data:
    dataset_name: parquet
    parquet_paths: /root/outputs/phimm_gen_chunk/part-*.parquet

    pre_process:
      output_egs_limit: 50
      filter_by_wer:
        wer_range: [0.0, 0.5]
    cache_name: auto_train
    num_proc: 1
    add_rare_keywords:
      common_file: /home/boren/data/librispeech_biasing/words/all_words.count.txt
      common_num: 1000
    add_prompt:
      task: asr
      # forced: True
    post_process:
      input_egs_limit: 100
      filter_by_keywords:
        min_num: 1
      output_egs_limit: 40
      verl_format:
        prompt_key: prompt
      add_field:
        fields:
          data_source: asr

  train_files: null
  val_files: null
  trust_remote_code: true
  max_prompt_length: 8192
  max_response_length: 1024
  train_batch_size: 8
  gen_batch_size: 8
  val_batch_size: 1024
  shuffle: false
  custom_cls:
    path: recipe/phimm/data/rl_dataset.py
    name: RLHFDataset
  eval_num_examine: 3
  train_num_examine: 1
