hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - data/train_data/ls_bias
  - data/val_data/ls_bias
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  reward_kwargs:
    beta: 5 # score = WER + beta*B-WER
    choice: "err" # "err", "acc", "wer"
    text_norm: simple_with_tag # english (default), identity, lower, basic, simple, simple_with_tag
    unit: char # word (default), char

algorithm:
  filter_groups:
    enable: false
  norm_adv_by_std_in_grpo: False
  # norm_adv_by_mean_in_grpo: False

actor_rollout_ref:
  rollout:
    n: 8
    gt_rollout: true
    temperature: 1.2
  actor:
    loss_agg_mode: seq-mean-token-sum-norm

  model:
    path: ${oc.env:DATA_PATH}/boren/data/ckp/hf_models/phi-libri_ft_m1000_p8_new-QpHq/5000_hf

data:
  # train_batch_size: ${eval:8*trainer.nnodes*trainer.n_gpus_per_node}
  # gen_batch_size: ${data.train_batch_size}
  train_batch_size: 64
  total_training_steps: 2200 # ~= 140k samples with bs64, 0.5 epoch
