hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - data/val_data/openasr_en
  - _self_

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/boren/data/ckp/hf_models/Phi4-7b-STT-2603-SR2
    lora_rank: 0
    target_modules: null
    exclude_modules: null
    trainable_params: [model.layers, model.norm, lm_head]
  actor:
    fsdp_config:
      param_offload: false
      optimizer_offload: false
      use_orig_params: true
  ref:
    fsdp_config:
      param_offload: true

trainer:
  resume_mode: resume_path
  resume_from_path: az://orngwus2cresco/data/boren/outputs/verl_repeat/remax_ls_raw_rp_edge_en_full/global_step_20
