hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
  verbose:
    - recipe.phimm.data.rl_dataset
defaults:
  - eval_asr
  - data/val_data/librispeech_h100
  - _self_

actor_rollout_ref:
  model:
    path: ${oc.env:DATA_PATH}/boren/data/ckp/hf_models/phi4-7b-fast-api-s2-final-v4
  rollout:
    tensor_model_parallel_size: 2
    gpu_memory_utilization: 0.8
