hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - _self_

actor_rollout_ref:
  model:
    path: ${oc.env:DATA_PATH}/users/boren/data/ckp/hf_models/Phi-4-multimodal-instruct
