hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - grpo_asr
  - data/train_data/gen_ls_raw_wer_gt20
  - data/val_data/spgispeech_repeat
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  reward_kwargs:
    alpha: 1
    beta: 0
    choice: "err"
    text_norm: english
    unit: word

actor_rollout_ref:
  rollout:
    n: 4
    gt_rollout: true
    temperature: 1.2
    calculate_log_probs: True
  actor:
    tis_imp_ratio_cap: 5
    optim:
      lr: 5e-6
  model:
    path: ${oc.env:DATA_PATH}/boren/data/ckp/hf_models/phi4-7b-fast-api-s2-final-v4
algorithm:
  adv_estimator: remax
data:
  train_batch_size: 64
trainer:
  total_epochs: 1
  # total_training_steps: 100
  test_freq: 10
  val_before_train: true
