hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - gen_asr
  - data/train_data/ls_raw_trim_tail
  - _self_

model:
  path: az://orngwus2cresco/data/boren/data/ckp/hf_models/Phi4-7b-STT-2603-SR2

data:
  batch_size: 512
  output_path: az://orngwus2cresco/data/boren/data/verl/gen_filtered/ls_raw_trim_tail_wer10
  output_split_size: 10000

rollout:
  temperature: 0.0
  gpu_memory_utilization: 0.8
