hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - gen_asr
  - /data/train_data/ls_rare_nonempty_verb
  - _self_

model:
  path: az://orngwus2cresco/data/boren/outputs/v2607_earning/remax_2607v1a_earning_fy27_s1k_bs256_v0_n1_r256_g16/global_step_650/qwen_hf/

trainer:
  nnodes: 2

data:
  output_path: az://orngwus2cresco/data/boren/data/verl/gen_qwen/2607v1a_earning_step650/ls_rare_nonempty_verb_g16
