hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - grpo_asr_full
  - data/train_data/gen_ls_raw_rp_edge
  - data/val_data/openasr_part0
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_edge.py
  name: compute_score
  reward_kwargs:
    betas:
      edge: 1

val_reward:
  custom_reward_function:
    path: recipe/phimm/reward/asr_edge.py
    name: eval_score

actor_rollout_ref:
  rollout:
    n: 16
    gt_rollout: true
    temperature: 1.2
    calculate_log_probs: True
    use_rollout_log_probs_as_old: true
  actor:
    tis_imp_ratio_cap: 5
    ppo_micro_batch_size_per_gpu: 8
    optim:
      lr: 5e-6
  model:
    path: az://orngwus2cresco/data/boren/data/ckp/hf_models/Phi4-7b-STT-2603-SR2
algorithm:
  adv_estimator: remax
  norm_adv_in_remax: l2
  use_kl_in_reward: true
  kl_penalty: low_var_kl
  kl_ctrl:
    type: adaptive
    kl_coef: 0.1
    target_kl: 0.1
    horizon: 100
data:
  train_batch_size: 64
trainer:
  nnodes: 1
  total_epochs: 1
  test_freq: 10
  save_freq: 10
  val_before_train: false
  dedup_responses: true
