hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - gen_asr
  - data/train_data/mix_cv15_n1k_task3
  - _self_

model:
  path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2607/amlt-results/fast-llm-2607-qwen3-5-9b-s2-data-v3.4-sr-afteraudio-lexical-fix/50000/qwen_hf/
  trust_remote_code: false

rollout:
  dtype: auto
  engine_kwargs:
    vllm:
      quantization: fp8

trainer:
  nnodes: 2
  n_gpus_per_node: 8

data:
  model_version: 2607
  output_path: az://orngwus2cresco/data/boren/data/verl/gen_qwen/2607v1/mix_cv15_n1k_task3