hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - data/val_data/openasr_ml
  - _self_

val_reward:
  custom_reward_function:
    path: recipe/phimm/reward/asr_eval.py
    name: openasr_eval

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/boren/data/ckp/hf_models/Phi4-7b-STT-2603-SR2

trainer:
  resume_mode: resume_path
  resume_from_path: az://orngwus2cresco/data/boren/outputs/verl_repeat/remax_dapo_brackets_oss_e10_v1/global_step_180
