hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_base
  - /data/val_data/earnings_aa_pre_chunk
  - _self_
