defaults:
  - base
  - /data/train_data/ls_raw
  - _self_

val_reward:
  reward_manager: dapo
  reward_kwargs: null
  custom_reward_function:
    path: recipe/phimm/reward/asr_eval.py
    name: openasr_eval
    reward_kwargs:
      version: 2607

data:
  version: 2607
  return_multi_modal_inputs: false
  shuffle: false
  use_interleave: false
  dataloader_num_workers: 8
  prefetch_factor: 4
  persistent_workers: true
  val_batch_size: 512

actor_rollout_ref:
  rollout:
    name: vllm
    max_num_seqs: 48
    gpu_memory_utilization: 0.9
  model:
    lora_rank: 0
    lora_alpha: 0
    target_modules: null
  actor:
    use_kl_loss: false

trainer:
  project_name: whisper_eval
  val_only: true
  val_before_train: true
  nnodes: 1
