hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_base
  - /data/val_data/openasr_2606_verb
  - _self_

trainer:
  nnodes: 2
