hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - data/train_data/earningscall-fy27-en-us-batches-tts-clean
  - /data/val_data/earnings_aa_chunked
  - _self_

reward_functions:
  asr_measure:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2609
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        keyword: {beta: 3.0}
        lang: {beta: 1.0}
        fmt: {beta: 1.0}

reward_function_by_data_source:
  earning_fy27_verb: asr_measure
  earning_fy27_lex: asr_measure
  earnings_tts_clean_verb: asr_measure
  earnings_tts_clean_lex: asr_measure

actor_rollout_ref:
  actor:
    kl_loss_coef: 0.005
  rollout:
    n: 16
    temperature: 1.0
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2609/amlt-results/fast-llm-2609-qwen9b-flashenc-mtp-s2-data-v3.5.3-r2/54000/qwen_hf/
    lora_rank: 128

data:
  train_batch_size: 64

trainer:
  nnodes: 4
  total_epochs: 30
  total_training_steps: 1000
  filter_nonfinite_log_probs: true
