hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - data/train_data/sr_fy22_rare02a
  - data/val_data/entity_rare
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_bias.py
  name: compute_score
  reward_kwargs:
    alpha: 1
    beta: 1 # score = alpha*WER + beta*B-WER
    choice: "err" # "err", "acc", "wer"
    text_norm: english # simple (default), identity, lower, basic, simple, simple_with_tag
    unit: word # word (default), char
    max_wer: 0.05 # max error allowed to get reward, otherwise -100

actor_rollout_ref:
  rollout:
    n: 4
    gt_rollout: true
    temperature: 1.2
    calculate_log_probs: True # required by TIS
  actor:
    tis_imp_ratio_cap: 5
    # optim:
    #   lr: 1e-5
    #   warmup_style: cosine
    #   min_lr_ratio: 0.1

  model:
    path: az://orngwus2cresco/data/boren/data/ckp/hf_models/phi4-7b-fast-api-s2-final-v4

data:
  max_prompt_length: 6000
  train_batch_size: 64
trainer:
  total_training_steps: 8800 # ~= 140k samples with bs64, 0.5 epoch
