hydra:
  searchpath:
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - data/train_data/ls_raw # not used
  - data/val_data/bias_entity_ls
  - _self_

actor_rollout_ref:
  rollout:
    n: 8
  model:
    path: az://orngwus2cresco/data/boren/data/ckp/hf_models/Phi-4-multimodal-instruct

data:
  max_prompt_length: 8192 # requred by 7b model

trainer:
  val_only: True
  n_gpus_per_node: 1
  nnodes: 1
