hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - /data/train_data/tts_times_tr_600
  - _self_

reward_functions:
  openml:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2607
      reduce: mean
      measures:
        char: {beta: 0.5}
        word: {beta: 0.5}
        keyword: {beta: 2.0}
        lang: {beta: 2.0}

reward_function_by_data_source:
  tts_times_tr_600: openml

actor_rollout_ref:
  actor:
    ppo_micro_batch_size_per_gpu: 2
    ppo_max_token_len_per_gpu: 2048

trainer:
  total_epochs: 200