hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - eval_base
  - data/val_data/openasr_2606_verb
  - _self_

val_reward:
  reward_function_by_data_source:
    ls_clean: openasr_en
    ls_other: openasr_en
    spgispeech: openasr_en
    ami: openasr_en
    gigaspeech: openasr_en
    voxpopuli_cleaned_aa: openasr_en
    earnings22_cleaned_aa_chunked: openasr_en

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/boren/outputs/ver_2607/remax_2607v1_openml_verb_s100_bs256_lid/global_step_100/qwen_hf/