hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - data/train_data/earnings_tts_jsonl_clean
  - _self_

reward_functions:
  asr_measure:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2607
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        keyword: {beta: 2.0, cut: 0.5}
        lang: {beta: 0.1, cut: 0.25}
        fmt: {beta: 0.1, cut: 0.5}

reward_function_by_data_source:
  earnings_tts_clean_verb: asr_measure
  earnings_tts_clean_lex: asr_measure

actor_rollout_ref:
  rollout:
    n: 4
    engine_kwargs:
      vllm:
        gdn_prefill_backend: triton
  model:
    path: az://orngwus2cresco/data/boren/outputs/ver_2607/remax_2607v1_openml_verb_s100_bs256_lid/global_step_100/qwen_hf/
    lora_rank: 256

data:
  train_batch_size: 256

trainer:
  nnodes: 2
  total_epochs: 30
  total_training_steps: 1000
