hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - data/train_data/earningscall-fy27-en-us-batches-tts-clean
  - _self_

reward_functions:
  asr_measure:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2607
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        keyword: {beta: 2.0, cut: 0.5}
        lang: {beta: 0.1, cut: 0.25}
        fmt: {beta: 0.1, cut: 0.5}

reward_function_by_data_source:
  earning_fy27_verb: asr_measure
  earning_fy27_lex: asr_measure
  earnings_tts_clean_verb: asr_measure
  earnings_tts_clean_lex: asr_measure

actor_rollout_ref:
  rollout:
    n: 8
    engine_kwargs:
      vllm:
        gdn_prefill_backend: triton
  actor:
    optim:
      lr: 1e-5
  model:
    path: az://orngwus2cresco/data/boren/outputs/ver_2607/remax_2607v1_openml_verb_s100_bs256_lid/global_step_100/qwen_hf/
    lora_rank: 256

data:
  train_batch_size: 256

trainer:
  project_name: v2607_earning
  experiment_name: remax_2607v1a_earning_batches_tts_s1k_bs256_n8_r256_g16_lr1e-5_kw2
  nnodes: 2
  total_epochs: 120
  total_training_steps: 1000
