hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - dapo_asr
  - data/train_data/qwen_bad_repeat_bracket_all
  - data/val_data/openasr_all_bad
  - _self_

custom_reward_function:
  path: recipe/phimm/reward/asr_edge.py
  name: compute_score
  reward_kwargs:
    gamma: 0.1
    unit: char

val_reward:
  custom_reward_function:
    path: recipe/phimm/reward/asr_eval.py
    name: openasr_eval


actor_rollout_ref:
  rollout:
    n: 8
    gt_rollout: false
    temperature: 1.0
    calculate_log_probs: True
    use_rollout_log_probs_as_old: true
    gpu_memory_utilization: 0.55
    enforce_eager: false # CUDA graph for perf; lower gpu_mem_util to fit compile
    max_num_seqs: 50
    
  actor:
    ppo_micro_batch_size_per_gpu: 8
    ppo_mini_batch_size: 64
    optim:
      lr: 5e-6
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2605/amlt-results/fast-llm-2605-qwen3-5-9b-s2-st-example/90000/qwen_hf/
algorithm:
  adv_estimator: remax
data:
  train_batch_size: 64
trainer:
  nnodes: 1
  total_epochs: 1
  test_freq: 10
  save_freq: 10
  val_before_train: true
  dedup_responses: false
