# OpenASR-ML Hindi and Dutch verbatim evaluation without language hints.
hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - eval_base
  - _self_

actor_rollout_ref:
  model:
    lora_rank: 128

data:
  val_data:
    - dataset_name: jsonl
      jsonl_paths: az://orngwus2cresco/data/boren/data/openasr_ml_jsonl/monsoon/hi_in/data.jsonl
      cache_name: auto_openasr_ml_verb_monsoon_hi_in_jsonl
      add_task_info:
        task: lang_asr_verb
        language: Hindi
      post_process:
        add_field:
          fields:
            data_source: monsoon_hi_in
        verl_format:
          prompt_key: prompt
          extra_keys: ["lattice"]

    - dataset_name: jsonl
      jsonl_paths: az://orngwus2cresco/data/boren/data/openasr_ml_jsonl/fleurs/nl/data.jsonl
      cache_name: auto_openasr_ml_verb_fleurs_nl
      add_task_info:
        task: lang_asr_verb
        language: Dutch
      post_process:
        add_field:
          fields:
            data_source: nl_fleurs
        verl_format:
          prompt_key: prompt

    - dataset_name: jsonl
      jsonl_paths: az://orngwus2cresco/data/boren/data/openasr_ml_jsonl/mcv/nl/data.jsonl
      cache_name: auto_openasr_ml_verb_mcv_nl
      add_task_info:
        task: lang_asr_verb
        language: Dutch
      post_process:
        add_field:
          fields:
            data_source: nl_mcv
        verl_format:
          prompt_key: prompt

    - dataset_name: jsonl
      jsonl_paths: az://orngwus2cresco/data/boren/data/openasr_ml_jsonl/mls/nl/data.jsonl
      cache_name: auto_openasr_ml_verb_mls_nl
      add_task_info:
        task: lang_asr_verb
        language: Dutch
      post_process:
        add_field:
          fields:
            data_source: nl_mls
        verl_format:
          prompt_key: prompt
