hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - eval_base
  - /data/val_data/openasr_ml_verb_langhint
  - _self_

actor_rollout_ref:
  model:
    lora_rank: 128
