hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - eval_base
  - /data/val_data/openasr_verb_noprefix
  - _self_

val_reward:
  reward_function_by_data_source:
    ls_clean: openasr_en
    ls_other: openasr_en
    spgispeech: openasr_en
    ami: openasr_en
    gigaspeech: openasr_en
    voxpopuli_cleaned_aa: openasr_en
    earnings22_cleaned_aa_chunked: openasr_en
