# Train OpenML only for 100 steps with a constant learning rate.
hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - /data/train_data/openml_verb_noreps_langhint@_ml_train
  - /data/val_data/earnings22_verb_langhint@_earning_val
  - /data/val_data/openasr_ml_bad_fmt_lang_bracket_langhint@_ml_val
  - _self_

reward_functions:
  openml:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2609
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        lang: {beta: 0.5}
        fmt: {beta: 0.5}
        bracket: {beta: 1.0}

reward_function_by_data_source:
  openml: openml

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2609/amlt-results/fast-llm-2609-qwen9b-flashenc-mtp-s2-data-v3.5.4-r2/54000/qwen_hf
  actor:
    kl_loss_coef: 0.005
    optim:
      lr: 3.0e-6
      warmup_style: constant
      lr_warmup_steps: 0
  rollout:
    n: 8

algorithm:
  remax_advantage_mask: edit_boundary

data:
  data_source:
    openml: {num_epoch: 1, shuffle: true}
  train_data:
    - ${_ml_train}
  val_data:
    - ${_earning_val}
    - ${_ml_val}
  train_batch_size: 64
  shuffle: false

trainer:
  nnodes: 4
  total_epochs: 30
  total_training_steps: 100
