hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - data/train_data/mix_cv15_all_openml_verb
  - /data/val_data/mixlang_openml_earning
  - _self_

reward_functions:
  openml:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2609
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        lang: {beta: 1.0, cut: 0.5}
        fmt: {beta: 1.0, cut: 0.5}
        bracket: {beta: 1.0, cut: 0.5}
  mix:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2609
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        lang: {beta: 1.0, cut: 0.25}
        fmt: {beta: 1.0, cut: 0.5}

reward_function_by_data_source:
  mix: mix
  mix_cv15_all: mix
  openml: openml

actor_rollout_ref:
  model:
    lora_rank: 256
  rollout:
    n: 4
    gt_rollout: true

data:
  train_batch_size: 256

trainer:
  total_epochs: 30
  total_training_steps: 1000
  default_hdfs_dir: az://orngwus2cresco/data/boren/outputs/${trainer.project_name}/${trainer.experiment_name}_qwen9b_step45000_restart_20260928_2214
  default_local_dir: ${oc.env:HOME}/checkpoints/${trainer.project_name}/${trainer.experiment_name}_qwen9b_step45000_restart_20260928_2214
