hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - /data/train_data/mix_cv15_all_openml_verb_noreps_langhint
  - /data/val_data/mixlang_openml_langhint
  - _self_

reward_functions:
  openml:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2609
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        lang: {beta: 0.5}
        fmt: {beta: 0.2}
        bracket: {beta: 1.0}
  mix:
    path: recipe/phimm/reward/asr_measure.py
    name: compute_score
    reward_kwargs:
      version: 2609
      reduce: mean
      measures:
        char: {beta: 1.0}
        word: {beta: 1.0}
        lang: {beta: 0.5}
        fmt: {beta: 0.2}

reward_function_by_data_source:
  mix: mix
  mix_cv15_all: mix
  openml: openml

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2609/amlt-results/fast-llm-2609-qwen9b-flashenc-mtp-s2-data-v3.5.3-r2/54000/qwen_hf/
    lora_rank: 128
  rollout:
    n: 4
    gt_rollout: true

data:
  train_batch_size: 128

trainer:
  total_epochs: 30
  total_training_steps: 1000
