hydra:
  searchpath:
    - file://verl/trainer/config
defaults:
  - dapo_asr_new
  - _self_
  - data/librispeech

data:
  custom_cls:
    path: verl/utils/dataset/audio/rl_dataset.py
    name: RLHFDataset
  eval_num_examine: 5
  train_num_examine: 1
  train_batch_size: ${batch_size}
  gen_batch_size: ${gen_batch_size}
custom_reward_function:
  path: recipe/phimm/reward/asr.py
  name: compute_score
  # reward_kwargs:
  #   beta: 1.0
actor_rollout_ref:
  model:
    lora_rank: 320
    lora_alpha: 640
    target_modules: "model.layers.*(qkv_proj|o_proj|gate_up_proj|down_proj).*"
    exclude_modules: "model.embed_tokens_extend.*" # must have
    path: /root/data/ckp/hf_models/phi4_mm_bias_merged
    enable_gradient_checkpointing: True
  actor:
    ppo_mini_batch_size: 1024
    ppo_micro_batch_size_per_gpu: ${batch_size}
    entropy_coeff: 0
    optim:
      lr: 1e-5
      min_lr_ratio: 0.1
  rollout:
    n: 8
    log_prob_micro_batch_size_per_gpu: ${batch_size}
    gpu_memory_utilization: 0.8
trainer:
  experiment_name: phimm-test
  total_epochs: 1

batch_size: 8
gen_batch_size: 16
