hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - dapo_asr
  - _self_

actor_rollout_ref:
  model:
    lora_rank: 320
    lora_alpha: 640
    # target_modules: "model.layers"
    target_modules: "((layers.*self_attn\\.(qkv|o)_proj)|(layers.*mlp\\.(gate_up|down)_proj))"
  rollout:
    load_format: safetensors
trainer:
  experiment_name: dapo-phimm-test-lora

train_bs: 8
n_rollout: 5
gen_bs: 16
train_files: /home/boren/data/parquet/ls_clean_sc1k_fn1_h100.parquet
val_files: /home/boren/data/parquet/ls_clean_sc1k_fn1_h100.parquet
model_path: /home/boren/data/ckp/hf_models/phi4_mm_bias_merged
