defaults:
  - dapo_asr
  - data/train_data/ls_raw
  - data/val_data/bias_entity_ls
  - _self_


val_reward:
  custom_reward_function:
    path: recipe/phimm/reward/asr_edge.py
    name: openasr_eval


data:
  # Parallelize remote audio fetch and decoding during validation.
  dataloader_num_workers: 8
  prefetch_factor: 4
  persistent_workers: true
  val_batch_size: 512


actor_rollout_ref:
  rollout:
    max_num_seqs: 48
    gpu_memory_utilization: 0.9


trainer:
  val_only: True
  val_before_train: True
  nnodes: 1
  # n_gpus_per_node: 4 # must be same as training, fix later
