defaults:
  - eval_asr
  - _self_

actor_rollout_ref:
  model:
    lora_rank: 0
    target_modules: null
    exclude_modules: null
    trainable_params: [model.layers, model.norm, lm_head]
  actor:
    fsdp_config:
      param_offload: true
      optimizer_offload: false
      use_orig_params: true
  rollout:
    gpu_memory_utilization: 0.8
  ref:
    fsdp_config:
      param_offload: true
