defaults:
  - dapo_asr
  - _self_

algorithm:
  filter_groups:
    enable: false

actor_rollout_ref:
  model:
    lora_rank: 0 # disable lora
    trainable_params: [model.layers]  # all layers are frozen