hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - data/val_data/ls
  - _self_

val_reward:
  custom_reward_function:
    path: recipe/phimm/reward/asr_bias.py
    name: eval_score

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2607/amlt-results/fast-llm-2607-qwen3-5-9b-s2-data-v3.4-sr-afteraudio-lexical-fix/50000/qwen_hf/

data: