hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - long_eval_asr
  - data/val_data/digits_tier1
  - _self_

reward_functions:
  digits:
    path: pkg://recipe.phimm.reward.digits_measure
    name: eval_score
reward_function_by_data_source:
  dede_digits_random: digits
  dede_digits_repeat: digits
  enus_digits_random: digits
  enus_digits_repeat: digits
  eses_digits_random: digits
  eses_digits_repeat: digits
  frfr_digits_random: digits
  frfr_digits_repeat: digits
  itit_digits_random: digits
  itit_digits_repeat: digits
  jajp_digits_random: digits
  jajp_digits_repeat: digits
  kokr_digits_random: digits
  kokr_digits_repeat: digits
  ptbr_digits_random: digits
  ptbr_digits_repeat: digits
  zhcn_digits_random: digits
  zhcn_digits_repeat: digits

model:
  path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2607/amlt-results/fast-llm-2607-qwen3-5-9b-s2-data-v3.4-sr-afteraudio-lexical-fix/50000/qwen_hf/

data:
  model_version: 2607
  output_path: az://orngwus2cresco/data/boren/data/verl/eval/qwen_2607v1_50000_lexical_fix/digits_tier1

val_reward:
  group_segment: false
