hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - data/val_data/openasr_ml
  - _self_

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2605/amlt-results/fast-llm-2605-qwen3-5-9b-s2-st-example/90000/qwen_hf/
  rollout:
    enforce_eager: false
    gpu_memory_utilization: 0.6

trainer:
  resume_mode: resume_path
  resume_from_path: az://orngwus2cresco/data/boren/outputs/verl_repeat/remax_qwen_bad_repeat_bracket_all_e1/global_step_113
  #
