hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - data/val_data/openasr_h100
  - _self_

actor_rollout_ref:
  actor:
    use_remove_padding: false
    fsdp_config:
      model_dtype: bf16
      wrap_policy:
        transformer_layer_cls_to_wrap:
          - Qwen3_5DecoderLayer
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2605/amlt-results/fast-llm-2605-qwen3-5-9b-s2-st-example/20000/qwen35-audio-hf/
    external_lib: vllm_qwen35_audio
    lora_rank: 0
    override_config:
      attn_implementation: sdpa
  rollout:
    tensor_model_parallel_size: 1
    gpu_memory_utilization: 0.55
    max_model_len: 4096
    max_num_seqs: 8
    max_num_batched_tokens: 8192
    enable_chunked_prefill: true
    stop: null
    stop_token_ids: [248044, 248046]
    engine_kwargs:
      vllm:
        limit_mm_per_prompt:
          audio: 1

data:
  audio_token: "<|audio_start|>\n"
  raw_prompt: |
    <|im_start|>user
    <|audio_start|>
    Detect the language and transcribe the audio into text.<|im_end|>
    <|im_start|>assistant
  max_prompt_length: 3584
  val_batch_size: 8

ray_kwargs:
  ray_init:
    runtime_env:
      env_vars:
        QWEN35_AUDIO_DISABLE_CUDNN: "1"
        VLLM_WORKER_MULTIPROC_METHOD: spawn
        VLLM_PLUGINS: qwen35_audio
        LD_LIBRARY_PATH: /root/.pyenv/versions/3.12.9/lib/python3.12/site-packages/nvidia/nvshmem/lib
