hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  - eval_asr
  - data/val_data/openasr
  - _self_

actor_rollout_ref:
  rollout:
    val_kwargs:
      repetition_penalty: 1.0
      no_repeat_ngram_size: 15
  model:
    path: az://orngwus2cresco/data/boren/data/ckp/hf_models/Phi4-7b-STT-2603-SR2
