hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config
defaults:
  # Run validation-only generation through trainer v1.
  - long_eval_asr
  - data/val_data/openasr_ml_verb_de_fleurs
  - _self_

val_reward:
  reward_functions:
    openasr:
      path: pkg://recipe.phimm.reward.asr_edge
      name: openasr_eval
  reward_function_by_data_source:
    de_fleurs: openasr

model:
  path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2607/amlt-results/fast-llm-2607-qwen3-5-9b-s2-data-v3.4-sr-afteraudio-lexical-fix/50000/qwen_hf

actor_rollout_ref:
  rollout:
    tensor_model_parallel_size: 1

rollout:
  n_gpus_per_node: 8

data:
  max_prompt_length: 1024
  max_response_length: 512
  output_path: az://orngwus2cresco/data/boren/data/verl/eval/qwen_2607v1_50000_lexical_fix/openasr_ml_verb_de_fleurs
