hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://recipe/phimm/config/base
    - file://verl/trainer/config

defaults:
  - eval_asr
  - _self_

val_reward:
  custom_reward_function:
    path: recipe/phimm/reward/asr_bias.py
    name: eval_score

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/speech/projects/phi-fastllm-2607/amlt-results/fast-llm-2607-qwen3-5-9b-s2-data-v3.4-sr-afteraudio-lexical-fix/50000/qwen_hf/

data:
  model_version: 2607
  max_prompt_length: 4096
  val_batch_size: 64
  val_data:
    - dataset_name: ls_bias
      jsonl_path: az://orngwus2cresco/data/boren/data/librispeech_biasing/ref/test-other.biasing_500.jsonl
      data_dir: az://orngwus2cresco/data/boren/data/
      cache_name: auto_other_500
      bias_key: distractors
      post_process:
        add_field:
          fields:
            data_source: other_500
        verl_format:
          prompt_key: prompt
