hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - eval_base
  - /data/val_data/mix_openml_aa_ter30
  - _self_

val_reward:
  aa_reward_function: openasr_ml
