hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - eval_base
  - /data/val_data/name_fy22_10k
  - _self_

data:
  dataloader_num_workers: 4
  prefetch_factor: 2
