defaults:
  - ../base@_here_
  - _self_

data:
  train_data: ${data.val_data}
  shuffle: false
  use_interleave: false
  dataloader_num_workers: 8
  prefetch_factor: 4
  val_batch_size: 256

trainer:
  validation_resume: true
  validation_resume_save_freq: 2
  project_name: v2609_ls_eval
  val_only: true
  val_before_train: true
