hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base_eval
  - /data/val_data/mix_openml_aa
  - _self_

val_reward:
  reward_function_by_data_source:
    mixlang_fy26q2: inhouse_zh
    de_fleurs: openasr_ml
    fr_fleurs: openasr_ml
    it_fleurs: openasr_ml
    es_fleurs: openasr_ml
    pt_fleurs: openasr_ml
    de_mcv: openasr_ml
    fr_mcv: openasr_ml
    it_mcv: openasr_ml
    es_mcv: openasr_ml
    fr_mls: openasr_ml
    it_mls: openasr_ml
    es_mls: openasr_ml
    pt_mls: openasr_ml
    earnings22_cleaned_aa: openasr_en
    voxpopuli_cleaned_aa: openasr_en

actor_rollout_ref:
  model:
    path: az://orngwus2cresco/data/boren/outputs/ver_2607/remax_2607v1_openml_verb_s100_bs256_lid/global_step_100/qwen_hf/