hydra:
  searchpath:
    - file://recipe/phimm/config
    - file://verl/trainer/config
defaults:
  - base
  - data/train_data/nonspeech_random_language_v0_lid1
  - _self_

data:
  train_batch_size: 64

actor_rollout_ref:
  rollout:
    gt_rollout: true
    gpu_memory_utilization: 0.7

trainer:
  total_training_steps: 100